### ISSUE TITLE
jsapi ticket

### ISSUE THREAD

**Issue by imyelo** [node-webot/wechat-api#11]
http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E9.99.84.E5.BD.951-JS-SDK.E4.BD.BF.E7.94.A8.E6.9D.83.E9.99.90.E7.AD.BE.E5.90.8D.E7.AE.97.E6.B3.95

**Comment by mani95lisa** [comment]
+1

**Comment by imyelo** [comment]
https://github.com/node-webot/wechat-api/pull/12#discussion_r22768210
