### ISSUE TITLE
获得全局token的例子有点问题

### ISSUE THREAD

**Issue by vimer** [node-webot/wechat-api#129]
var api = new API('appid', 'secret', function (callback) {
  // 传入一个获取全局token的方法
  fs.readFile('access_token.txt', 'utf8', function (err, txt) {
    if (err) {return callback(err);}
    callback(null, JSON.parse(txt));
  });
}, function (token, callback) {
  // 请将token存储到全局，跨进程、跨机器级别的全局，比如写到数据库、redis等
  // 这样才能在cluster模式及多机情况下使用，以下为写入到文件的示例
  fs.writeFile('access_token.txt', JSON.stringify(token), callback);
});

只要建个空白文件 access_token.txt   就可以了吗？ 首先得把token写入进去吧，后面的writeFile 没看到被调用哦

**Comment by vimer** [comment]
按道理应该是先保存token到文件 然后读文件吧，但是没看到 store被调用了

**Comment by XGHeaven** [comment]
writeFile 只有在从服务器上获取 token 的时候才会调用

**Comment by vimer** [comment]
@XGHeaven 那么我使用这段代码的时候 ，是开始建立一个空的文件，需要先手工把token 写入进去吗？ 不然读出来的文件是空的

**Comment by JacksonTian** [comment]
这个只是个例子。用redis。

**Comment by XGHeaven** [comment]
@vimer 是空的，你直接回调一个空就可以，api内部会自动进行判断的。如果cb的内容是空，会自动从微信服务器获取数据的
