### ISSUE TITLE
循环调用api.sendText()

### ISSUE THREAD

**Issue by vimer** [node-webot/wechat-api#130]
当我循环调用这个api的时候 发现access_token 在不断的覆盖，很快2000个就用完了，为什么循环调用一个api会出现这个问题呢？

**Comment by XGHeaven** [comment]
你是不是写了存储和读取的回调函数，你可能没有处理好这个问题

**Comment by vimer** [comment]
@XGHeaven 
![](http://ww1.sinaimg.cn/large/744e593bgw1f24snalpwcj211u06mgmn.jpg)

**Comment by vimer** [comment]
@XGHeaven 就是上面这种代码

**Comment by XGHeaven** [comment]
我的意思是你是不是在实例化 api 的时候，传入的读取和存储的回调函数出现了一些问题？能上一下代码么？

**Comment by vimer** [comment]
@XGHeaven 
![](http://ww1.sinaimg.cn/large/744e593bgw1f24su0vvvgj212w0nwaeo.jpg)

代码其实挺简单，就是循环openid 推送数据，但是每循环一次 就使用一次 token

**Comment by JacksonTian** [comment]
这样子调用肯定会出问题的。

**Comment by vimer** [comment]
@JacksonTian 那怎么循环openid进行推送呢

**Comment by JacksonTian** [comment]
api.getLatestToken(function () {
  for () {
    api.sendText();
  }
});

**Comment by vimer** [comment]
@JacksonTian  我现在就是这样做的 预先获取到token 然后 传给sendText

**Comment by JacksonTian** [comment]
不需要你每次都这么做。应用启动的时候做一次就行了。

**Comment by vimer** [comment]
恩，另外 现在服务号 给用户进行推送也是需要 交互在 24小时之内吗，很多用户都是没在24小时之内交互的 隔一天的。

**Comment by JacksonTian** [comment]
这些规则 仔细看腾讯的文档

**Comment by XGHeaven** [comment]
@JacksonTian 我记得可能会发生这样的问题，就是在重新获取token的时候，又发送了一次请求，这次请求一样需要重新获取token，就会获取两次token，而发生覆盖
