### ISSUE TITLE
getGoods 微信小店获取商品信息失败

### ISSUE THREAD

**Issue by air-cc** [node-webot/wechat-api#131]
返回的错误信息是：name: 'WeChatAPIError', code: 44002 ；
感觉是微信那边的问题，我自己用postname手动打请求也是同样的错误信息。
求解？

**Comment by JacksonTian** [comment]
去看看微信的错误码 44002 代表什么意思。

**Comment by JacksonTian** [comment]
这就是微信服务端给你的报错信息
