### ISSUE TITLE
设置按钮总是报 socket hang up 

### ISSUE THREAD

**Issue by Wang-Kai** [node-webot/wechat-api#134]
朴大大，我想锻炼一下自己的node水平，所以没有用您的库。问题是这样的，我先是用**https.request** ，发送GET请求，拿到access_token，然后再request的end()回调函数中再次发送request POST请求，设置按钮，但是总是报** socket hang up**，调试了老半天了，求朴大大 指教，感激不尽！！！

**Comment by nick-ma** [comment]
off topic. 你可以看这个库的源代码来学习。
