### ISSUE TITLE
我的应用部署在内网，无法发起对微信api服务器地址的请求

### ISSUE THREAD

**Issue by qinchende** [node-webot/wechat-api#137]
如题，这种情况如何使用 wechat-api ？

**Comment by nick-ma** [comment]
通过设置代理来访问。
具体的方法请看 wechat-enterprise-api 的README。

2016-04-07 11:13 GMT+08:00 qinchende <notifications@github.com>:

**Comment by qinchende** [comment]
试过了，成功解决问题。

非常感谢！
