### ISSUE TITLE
增加微信硬件获取 qrcode

### ISSUE THREAD

**Issue by gengen1988** [node-webot/wechat-api#151]
我在做微信硬件的开发。微信硬件平台获取二维码的 API 与原有获取二维码的地址不一样。

``` text
http请求方式: POST
https://api.weixin.qq.com/device/create_qrcode?access_token=ACCESS_TOKEN
```

要不要支持微信硬件的 API？

参考：
http://iot.weixin.qq.com/wiki/new/index.html?page=3-4-4

**Comment by gengen1988** [comment]
我没注意到已经有了，不好意思

**Comment by gengen1988** [comment]
文档里没有：
http://doxmate.cool/node-webot/wechat-api/api.html

但是代码里有：
https://github.com/node-webot/wechat-api/blob/master/lib/api_device.js

所以是该更新文档还是更新代码？

**Comment by JacksonTian** [comment]
需要更新代码里的注解，然后根据注解生成文档。

**Comment by kainy** [comment]
https://wechat-api.kainy.cn/node-webot/wechat-api/api.html 用这个吧。 这个是可以的。
