### ISSUE TITLE
安装方法

### ISSUE THREAD

**Issue by csxrzeng** [node-webot/wechat-api#176]
使用npm的安装方法
npm install --save https://github.com/node-webot/wechat-api.git

一点参考，防止新手git clone 之后不知道如何处理，以及为如何添加到package.json而苦恼。

**Comment by JacksonTian** [comment]
直接 `npm install wechat-api --save` 不就好了吗

**Comment by csxrzeng** [comment]
不好意思，摆了个乌龙。使用的是另一个库。
https://github.com/markaii/open-wechat-api
