### ISSUE TITLE
AccessToken 有效性到达临界值时的并发问题

### ISSUE THREAD

**Issue by befinal** [node-webot/wechat-api#179]
API.prototype.preRequest 中

``` javascript
  if (token && (accessToken = AccessToken(token.accessToken, token.expireTime)).isValid()) {
    // 暂时保存toke
  } else {
    // 使用appid/appsecret获取token
    that.getAccessToken(callback);
  }
};
```

当token到达临界值变为无效时, 如果这时候并发非常大, 所有并发请求都会调用getAccessToken去获取新的token, 会不会导致调用频率的消耗?

**Comment by JacksonTian** [comment]
会。

**Comment by Asher-Tan** [comment]
所以能不能用个setTimeout在过期前10s就用主线程请求geng更新access_token ?

**Comment by JasonBoy** [comment]
@Asher-Tan 要是10s没有主动获取到怎么办？maybe API主动获取时，其他获取的请求只能先等待

**Comment by artofspeed** [comment]
做你自己的获取token的逻辑, 把它存储到database里，每过期前十分钟前让它refresh token一下。其他process只调用database的就可以。

**Comment by Asher-Tan** [comment]
@artofspeed  我比较倾向你这种方式
