### ISSUE TITLE
_sendNews 似乎不能用。 总是报44003

### ISSUE THREAD

**Issue by foxtail000** [node-webot/wechat-api#180]
在发送同样的json对象下，但是我自己自己写post是正确的，能正常发送到。

**Comment by JacksonTian** [comment]
难道不是该调用 .sendNews 吗

**Comment by foxtail000** [comment]
我是第三方平台。 因为我有现成的token了。 我直接用token new了一个新对象，将lib下的文件 mixin到对象里。

**Comment by JacksonTian** [comment]
你只要改get/save Token方法就好了吧。
