### ISSUE TITLE
生成带参数的二维码接口

### ISSUE THREAD

**Issue by jaydanluo** [node-webot/wechat-api#19]
我的需求是生成带参数的临时二维码。
研究了下官方的文档，好像只能通过sceneId去传整型参数。

场景值ID，临时二维码时为32位非0整型，永久二维码时最大值为100000（目前参数只支持1--100000）。

上面为官方文档的原文，临时二维码支持32位非0整型的场景值ID。

我这边用wechat-api的createTmpQRCode方法测试了下，在服务器后台可以通过req.weixin.EventKey拿到所传的场景值，格式类似为qrscene_1234。

但我发现如果场景值ID超过999999999九位数字后，到了后台会变成qrscene_0。
诚求各路大神指点。

**Comment by shiny** [comment]
搜索而来，记录下： 微信的 32位非零整型是 4294967295（unsigned）溢出后变成 4294967295。如果继续过大，则像 lz 说的变成 0。
