### ISSUE TITLE
超时不可用问题

### ISSUE THREAD

**Issue by ForeverPx** [node-webot/wechat-api#194]
nodejs隔段时间请求微信接口时，会出现请求接口超时的问题，且超时后该接口永远无法访问了，会一直返回超时。只有将nodejs重启才能解决。

请大神帮忙分析下

**Comment by JacksonTian** [comment]
可以调用setOpts方法加长timeout时间。

**Comment by ForeverPx** [comment]
但是为什么会出现这种现象呢？

**Comment by ForeverPx** [comment]
我这边超时一次之后就再也请求不成功了，大神有没有遇到过这种现象。

在出现这种现象的时候，用curl命令也是可以很快返回结果的，所以网络应该没问题。

**Comment by JacksonTian** [comment]
木有 = =

**Comment by superlbr** [comment]
我也遇到了，贴个日志给各位看看

`check send message times  id=16138
[Error: 1|跳转获取openid]
[sendMessage] 数据3068 type: trade_bill,3068,checkout
{ [WeChatAPIResponseTimeoutError: Request timeout for 5000ms, POST https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=h4PlwzWQfI9tuqR_Qpeuffki4hBVgs_rdfBOZv_MaG9R8hqQbsRJnXu5vnOdbasgQrfdKnqdA7meQqW3sO6dpmHxOltvHjYlA5b1F8JT6NbMY37QI4fq75l5g6AsfYpQQWRdACAWCX -1 (connected: true, keepalive socket: false)
headers: {}]
  name: 'WeChatAPIResponseTimeoutError',
  requestId: 59,
  data: undefined,
  path: '/cgi-bin/message/template/send?access_token=h4PlwzWQfI9tuqR_Qpeuffki4hBVgs_rdfBOZv_MaG9R8hqQbsRJnXu5vnOdbasgQrfdKnqdA7meQqW3sO6dpmHxOltvHjYlA5b1F8JT6NbMY37QI4fq75l5g6AsfYpQQWRdACAWCX',
  status: -1,
  headers: {},
  res: 
   { status: -1,
     statusCode: -1,
     headers: {},
     size: 0,
     aborted: false,
     rt: 5003,
     keepAliveSocket: false,
     data: undefined,
     requestUrls: [ 'https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=h4PlwzWQfI9tuqR_Qpeuffki4hBVgs_rdfBOZv_MaG9R8hqQbsRJnXu5vnOdbasgQrfdKnqdA7meQqW3sO6dpmHxOltvHjYlA5b1F8JT6NbMY37QI4fq75l5g6AsfYpQQWRdACAWCX' ] } }
check send message times  id=16139`

我看到其实wechat api是有灾备的
![qq20161018-0](https://cloud.githubusercontent.com/assets/8142164/19461892/1610f988-951b-11e6-9707-2c5cc6404e60.png)

**Comment by JacksonTian** [comment]
这个文档事那里来的

**Comment by superlbr** [comment]
http://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1465199793_BqlKA&token=&lang=zh_CN @JacksonTian

**Comment by superlbr** [comment]
还有能不能接口超额了，自动清零，http://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433744592&token=&lang=zh_CN

**Comment by JacksonTian** [comment]
增加 setEndpoint & clearQuota 方法
