### ISSUE TITLE
客服相关接口不可用

### ISSUE THREAD

**Issue by zhirong2016** [node-webot/wechat-api#196]
![image](https://cloud.githubusercontent.com/assets/18457728/19295897/338662ec-906a-11e6-9f96-5d09035391e1.png)
微信已升级客服接口  改了接口

**Comment by JacksonTian** [comment]
我们的API还是旧的吗？

**Comment by zhirong2016** [comment]
是的   现在API没有密码这个参数了
![image](https://cloud.githubusercontent.com/assets/18457728/19296960/d44557f8-9072-11e6-88b8-fea8f20d5ed4.png)

**Comment by JacksonTian** [comment]
欢迎 pull request。

**Comment by zhirong2016** [comment]
其实就是去掉密码就可以了   不过可能微信之后还会在支持   所以····
