### ISSUE TITLE
期待增加一个用户可用的 make 接口

### ISSUE THREAD

**Issue by dubiao** [node-webot/wechat-api#201]
希望增加一个用户可用的，类似 util 中 make所做，可以快速自己定义一个接口，这个接口定义后，在其它地方可以像调用 wechat-api接口一样方便的调用此接口。
重点是在定义这个接口时，里面可以快速地取到 token 等关键信息。
这样能解决当微信官方接口增加，而 wechat-api 没有更新时，自己写一个处理方法，而不用直接改代码
定义形式如下：

```` javascript
var API = require("wechat-api");
API.make('updateMemberCardUserInfo', function (info, callback) {
  var url = 'https://api.weixin.qq.com/card/membercard/updateuser?access_token=' + this.token.accessToken;
  var data = info;
  this.request(url, postJSON(data), wrapper(callback));
});
````
又因为大部分时候都是 post 一个 json，所以也可以有简单版本：

```` javascript
var API = require("wechat-api");
API.make('updateMemberCardUserInfo', 'https://api.weixin.qq.com/card/membercard/updateuser');
````
三个参数分别为 定义的方法名，api 的 url，回调。
按照微信接口目前的逻辑，应该自动给 url 加上 token。

用这两种中的任何一种定义方法后，都可以通过`api.updateMemberCardUserInfo(info, callback);` 来调用这个方法。

**Comment by JacksonTian** [comment]
可以做的。如果能实现的话欢迎直接PR。

**Comment by dubiao** [comment]
@JacksonTian 我快写好了。方法签名用 `API.ext('functionName', 'url')` 怎么样？
在纠结用 make 还是 ext

**Comment by dubiao** [comment]
已提交 PR， #199 
两个 PR 合并为一个了。
