### ISSUE TITLE
群发接口推送文章接口返回报文 30002

### ISSUE THREAD

**Issue by trojanliu** [node-webot/wechat-api#215]
你好,
微信公众号群发接口推送文章, 接口返回报文 30002, 原创校验被判定为不能群发.

但是问题有:

1.该图文推送了两三个公众号, 但文章是原创的. 且都未进行原创声明.
2.再次推送其他公众号后, 接口报文状态 30002,  原创校验被判定为不能群发.
3. 使用微信官方后台 再次推送可以成功.

请问是否是我们API没升级导致.      原创校验是 微信2016年12月22日新增.

**Comment by JacksonTian** [comment]
发一下这个API的文档地址。

**Comment by trojanliu** [comment]
文档地址:
https://mp.weixin.qq.com/wiki?id=mp1481187827_i0l21&highline=%E5%8E%9F%E5%88%9B

**Comment by trojanliu** [comment]
原创问题.  原文作者禁止转载.   搞错了...
