### ISSUE TITLE
上传永久MP3文件报错

### ISSUE THREAD

**Issue by looping84** [node-webot/wechat-api#22]
1、MP3只有10k
2、临时素材的接口没有问题。

    api.uploadMedia("/material/a.mp3", "voice", function(err, result) {
      
        console.log(result);
    });
3、永久的报错

>{ [WeChatAPIRequestError: socket hang up (req "error"), POST  xxxxxXbM&type=voice -1
headers: {}]
  code: 'ECONNRESET',
  name: 'WeChatAPIRequestError',
  data: undefined,
  status: -1,
  headers: {},
  res: 
   { status: -1,
     statusCode: -1,
     headers: {},
     size: 0,
     aborted: false,
     rt: 1467 } }

**Comment by JacksonTian** [comment]
重试也不行么

**Comment by looping84** [comment]
不行啊。需要怎么debug下

**Comment by looping84** [comment]
抓的包
![Uploading m1.png . . .]()

**Comment by looping84** [comment]
抓的包，永久的

![抓的包]
(http://heyriacom.qiniudn.com/m1.png)

**Comment by looping84** [comment]
知道了，微信文档的地址错了。应该是这个，朴神改下吧。。。。。
https://api.weixin.qq.com/cgi-bin/material/add_material
