### ISSUE TITLE
请问是不是支持nodejs v6.10.2

### ISSUE THREAD

**Issue by wuyuanhao** [node-webot/wechat-api#225]
npm install wechat-api出错：

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/local/node-v6.10.2-linux-x64/bin/node" "/usr/local/node-v6.10.2-linux-x64/bin/npm" "install" "wechat-api"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: jekyll@1.0.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.0.0-beta1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'font-awesome'
npm ERR! notarget

**Comment by JacksonTian** [comment]
你是不是写错了版本啊

**Comment by wuyuanhao** [comment]
我也搞不清楚，后来把font-awesome卸载了，就可以了:)
不知道到底是什么原因
