### ISSUE TITLE
无限重复的post请求

### ISSUE THREAD

**Issue by yangjiedage** [node-webot/wechat-api#244]
开发了一个自动回复模板的功能，但服务器会一直接收post请求, 然后一直重复发送模板消息。
不知道是什么问题，麻烦大家解答一下

**消息模板的代码**
```
const sendTemp = function (options, callback) {
  var templateId = 'xxxxxxxxxxxxxxxxxxxxx'
  var url = ''
  var data = {
    "first": {
      "value":"消息获取成功",
      "color":"#173177"
    },
    "keyword1":{
      "value":"铁板烧",
      "color":"#173177"
    },
    "keyword2": {
      "value":"A11",
      "color":"#173177"
    },
    "keyword3": {
      "value":"22桌",
      "color":"#173177"
    },
    "keyword4": {
      "value":"30分钟",
      "color":"#173177"
    },
    "keyword5": {
      "value":"-",
      "color":"#173177"
    },
    "remark":{
      "value":"好吃好喝",
      "color":"#173177"
    }
  }
  api.sendTemplate(options.FromUserName, templateId, url, data, function(err, result) {
    if (!err) {
        callback && callback(result);
        // console.log(result)
    } else {
        console.log(err);
    }
  });
  //console.log('weixin', message)
}
router.post('/wechat', wechat(config, function (req, res, next) {
  var message = req.weixin;
  sendTemp(message, function(result) {
    res.send(result)
  })
}));
```
**服务接收到post请求之后的返回**
>POST /wechat?signature=xxxxxxxxxxxxxx&timestamp=1509469223&nonce=516407649&openid=xxxxxxxxx200 1588.109 ms - 45
POST /wechat?signature=xxxxxxxxxxxxxx&timestamp=1509469226&nonce=1874667043&openid=xxxxxxxxx 200 755.826 ms - 45
POST /wechat?signature=xxxxxxxxxxxxxx&timestamp=1509469227&nonce=440804969&openid=xxxxxxxxx 200 763.694 ms - 45
POST /wechat?signature=xxxxxxxxxxxxxx&timestamp=1509469228&nonce=540609154&openid=xxxxxxxxx 200 764.799 ms - 45
POST /wechat?signature=xxxxxxxxxxxxxx&timestamp=1509469230&nonce=1794803797&openid=xxxxxxxxx 200 775.944 ms - 45

**Comment by JacksonTian** [comment]
你的响应有问题把？

**Comment by yangjiedage** [comment]
@JacksonTian 是代码还是服务器的返回？
