### ISSUE TITLE
好凌乱的感觉

### ISSUE THREAD

**Issue by gwuhaolin** [node-webot/wechat-api#25]
看晕了

**Comment by gwuhaolin** [comment]
用起来还是很方便,赞!

**Comment by JacksonTian** [comment]
具体哪里凌乱，可以提出来 好方便改进。也是帮助其他使用者

发自我的 iPhone

**Comment by nick-ma** [comment]
看代码比看文档靠谱

2015-03-29 21:54 GMT+08:00 Jackson Tian <notifications@github.com>:
