### ISSUE TITLE
domain doxmate.cool is expired

### ISSUE THREAD

**Issue by airyland** [node-webot/wechat-api#258]
![image](https://user-images.githubusercontent.com/559179/51171247-5725ff80-18eb-11e9-93e2-14648e9fa97d.png)

**Comment by mywei1989** [comment]
文档域名过期了

**Comment by Mikasa33** [comment]
域名过期这个咋整。。

**Comment by Mikasa33** [comment]
已经恢复了

**Comment by kainy** [comment]
https://wechat-api.kainy.cn/node-webot/wechat-api/api.html 用这个吧。
