### ISSUE TITLE
获取二维码地址后，上传到临时素材报错，望指导。

### ISSUE THREAD

**Issue by SealedLove** [node-webot/wechat-api#259]
var QRCodeURL = api.showQRCodeURL(ticket);
var readStream = request(QRCodeURL);

api.uploadImageStream(readStream, function (err, data) {});

上传报错提示：WeChatAPIError: media data missing hint: [yCPm5a05345190]

请问怎么解决？

**Comment by JacksonTian** [comment]
业务错误。参考官方文档。
