### ISSUE TITLE
AccessToken框架会自动刷新吗?

### ISSUE THREAD

**Issue by gwuhaolin** [node-webot/wechat-api#27]
微信文档说AccessToken 7200S过期,getLatestToken()获得的AccessToken一定是没有过期的吗?
调用getLatestToken()时会去微信服务器那里更新一次AccessToken还是返回缓存的?
希望在文档里说明一下

**Comment by JacksonTian** [comment]
缓存的token如果没过期就返回缓存的，如果过期了 或者没有缓存的token就更新一次。

**Comment by nick-ma** [comment]
会。
对access token的save和load过程中，把expireTime也带进去。
wechat-api内部会自动判断的，快过期了，或者已经过期了，就去重新获取一个，然后自动调用save_token的方法保存。
