### ISSUE TITLE
为何没有用户分组删除接口呢？

### ISSUE THREAD

**Issue by strongme** [node-webot/wechat-api#32]
**如题**
>我看了下以为官方没有提供这个接口呢，是拉下了，还是有其他原因呢？
麻烦大神告下
只有下面这几个
* getGroups
* getWhichGroup
* createGroup
* updateGroup
* moveUserToGroup

**Comment by JacksonTian** [comment]
发下文档地址。

可能是新接口

发自我的 iPhone

**Comment by strongme** [comment]
>我看之前有个人写的也是没有这个实现~~，难道是有啥原因 呢？

* [现实现情况](http://doxmate.cool/node-webot/wechat-api/api.html#api_api_group)
* [官方](http://mp.weixin.qq.com/wiki/0/56d992c605a97245eb7e617854b169fc.html#.E5.88.A0.E9.99.A4.E5.88.86.E7.BB.84)

**Comment by JacksonTian** [comment]
很简单。这个借口是微信后来加的。

**Comment by JacksonTian** [comment]
fixed.

**Comment by strongme** [comment]
haha, easy for you, but a little bit trouble for us :+1: 
thanks ! :heart:
