### ISSUE TITLE
永久二维码请求无法发送字符串式的id

### ISSUE THREAD

**Issue by WangJunru** [node-webot/wechat-api#35]
当前请求永久二维码接口为：api.createLimitQRCode(100, callback);
而腾讯文档中：
永久二维码请求说明

http请求方式: POST
URL: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token=TOKEN
POST数据格式：json
POST数据例子：{"action_name": "QR_LIMIT_SCENE", "action_info": {"scene": {"scene_id": 123}}}
或者也可以使用以下POST数据创建字符串形式的二维码参数：
{"action_name": "QR_LIMIT_STR_SCENE", "action_info": {"scene": {"scene_str": "123"}}}

可以创建字符串形式的二维码参数。

**Comment by JacksonTian** [comment]
字符串是后续添加的功能吧。有兴趣提交pull request么

**Comment by JacksonTian** [comment]
`wechat-api@1.8.4`

**Comment by WangJunru** [comment]
在最新版本实现了？谢谢。

**Comment by JacksonTian** [comment]
yes

发自我的 iPhone
