### ISSUE TITLE
new API 异步问题

### ISSUE THREAD

**Issue by phevose** [node-webot/wechat-api#38]
因为项目的前后台分别在两个不同的node进程，下面是代码
1、 var api = new API(appid, appsecret, function(){....},  function(){....});
2、api.getFollowers(function(){....});

当实际执行时第二行代码总是在第一行还没获取到token就执行了，我想在 new API的回调函数中获取已经初始化完成的api，但是看了源码在调用getToken和saveToken后还要做对prefix等url赋值的操作，因此这时的api并没有初始化完成，我该如何解决这个问题？

**Comment by nick-ma** [comment]
首先，这东西（包括其他的api）是不能跨进程复用的。
其次，跨进程部署的时候，需要把accessToken放在数据库、文件、redis之类的共享的地方。
第三，如果你的前台和后台是2个独立的进程（即2个独立的，互不干扰的express工程），那么各自初始化自己的api就好了，无非他们对accessToken的读取和存储是一个位置就好。

**Comment by phevose** [comment]
我是第三种情况，在2个单独的进程汇总都使用如下代码初始化api
var api = new API(AppID, AppSecret, function (callback) {
		// 传入一个获取全局token的方法
		Weixin.findOne({'AppID':AppID},function(err,weixin){
			callback(null, weixin.access_token);//weixin.access_token包含accessToken和expireTime两个字段。
		});
	}, function (token, callback) {
		// 请将token存储到全局，跨进程、跨机器级别的全局，比如写到数据库、redis等
		// 这样才能在cluster模式及多机情况下使用，以下为写入到文件的示例
		Weixin.update({'AppID':AppID},{$set:{access_token:token}},function(err){
			if (err) return callback(err);
		});
	});

**Comment by phevose** [comment]
Weixin的schema结构：
        name:String,//微信名称
	number:{type:String,index:{unique: true}},//微信号
	AppID:{type:String,index:{unique: true}},
	AppSecret:String,
	access_token:{}

**Comment by phevose** [comment]
问题找到了
Weixin.update({'AppID':AppID},{$set:{access_token:token}},function(err){
        if (err) return callback(err);
        这里没有将token回传，加上callback(token);就正常了
});
