### ISSUE TITLE
关于Access Token的存储（access_token.txt不存在）

### ISSUE THREAD

**Issue by plantvsbirds** [node-webot/wechat-api#48]
README里面给的例子似乎不太对
如果在`readFile`时处理按照`fs.readFile('access_token.txt', 'utf8', function (err, txt) {
    if (err) {return callback(err);}` 这样处理错误的话，假如刚开始跑，没有`access_token.txt`文件就会一直报错，而不是去获取新Token
```
{"errno":34,"code":"ENOENT","path":"access_token.txt"}
```

我把它替换为`if (err) {return callback(null,null);}`之后就好了（参照默认callback的处理方式，这样会让他去请求一次access token），这样处理对么？

**Comment by JacksonTian** [comment]
你就不能在项目启动前touch一下这个文件么。

**Comment by plantvsbirds** [comment]
😂我怎么没想到呢。。我试试

**Comment by plantvsbirds** [comment]
嗯。。可以了，我发现光touch个空文件也不行。。

直接`JSON.parse`个空文件会直接挂掉，`touch`完还得顺带`echo "{}" > 那啥` 一下

**Comment by JacksonTian** [comment]
文档中的示例只是演示如何进行自定义的存取token。当然还有一些周边工作要做。
