### ISSUE TITLE
WeChatAPIError: access_token expired 线上环境报错

### ISSUE THREAD

**Issue by zaczhou** [node-webot/wechat-api#52]
我环境时常报错 WeChatAPIError: access_token expired

不知道什么原因，看了一些源码，感觉有对过期token的处理， 不知道是不是我在使用的时候有什么不对的地方，求解答

**Comment by zaczhou** [comment]
想到问题原因了

**Comment by JacksonTian** [comment]
什么原因？是不是多进程导致的？

**Comment by liangwenzhong** [comment]
@zaczhou 是什么原因？可以解析下吗？我现在也遇到类似的问题，我采用redis来存储token。然后用pm2来做cluster

**Comment by JacksonTian** [comment]
不要有别的渠道可以刷新token。

**Comment by liangwenzhong** [comment]
@JacksonTian 我目前只是使用了wechat-api 和wechat-oath、wechat这三个库。是否有冲突？目前没有其它刷新token的渠道。


	var wechatAPIClient = new WechatAPI(wechatConfig.mp.appId, wechatConfig.mp.appSecret, function(callback) {
		redisClient.get('wechat-token-ticket-' + wechatConfig.mp.appId, function(err, result) {
			if (err) return callback(err);
			callback(null, JSON.parse(result));
		});
	}, function(token, callback) {
		redisClient.set('wechat-token-ticket-' + wechatConfig.mp.appId, JSON.stringify(token));
		callback(null);
	});
	wechatAPIClient.registerTicketHandle(function(type, callback) {
		redisClient.get('wechat-token-ticket-' + type + '-' + wechatConfig.mp.appId, function(err, result) {
			if (err) return callback(err);
			callback(null, JSON.parse(result));
		});
	}, function(type, _ticketToken, callback) {
		redisClient.set('wechat-token-ticket-' + type + '-' + wechatConfig.mp.appId, JSON.stringify(_ticketToken));
		callback(null);
	});

以上是我目前的构造方法。我还registerTicketHandle。但是尽管我删除了。一样会有token是过期了，但是时间还没到。

**Comment by JacksonTian** [comment]
callback写到redis.set的参数里。

**Comment by liangwenzhong** [comment]
@JacksonTian 修改之后，依然会有时间还没过，token就过期的现象。是否有方案可以保证获取的是有效的token？

**Comment by JacksonTian** [comment]
你的并发有多大？

**Comment by liangwenzhong** [comment]
@JacksonTian 目前应用并发，大概100-200左右。
