### ISSUE TITLE
卡券调用问题，获得的cardExt，用于jssdk打开领取卡券的页面显示“签名错误”

### ISSUE THREAD

**Issue by shuhankuang** [node-webot/wechat-api#74]
如题
通过cardId获得的getCardExt，用于jssdk打开领取卡券的页面显示“签名错误”,

文档说
```
领取页面提示签名错误
核对签名时间戳是否和 card_ext 中的一致
```
但这个sign的timestamp是一样的

----
![831804737](https://cloud.githubusercontent.com/assets/251948/10445940/acd78948-71ab-11e5-90a0-76734f5ec143.jpg)

初始化jsconfig是正常的。

用获得的cardExt生成的cardList
```
wx.addCard({
      cardList: cardList,
      success: function (res) {
        alert('已添加卡券：' + JSON.stringify(res));
      }
    });
```

**Comment by shuhankuang** [comment]
返现问题了，传过去的某个参数未undefined, :x

**Comment by JacksonTian** [comment]
么么
