### ISSUE TITLE
代码中preRequest 当遇到40001时，不做任何操作就再去调用preRequest貌似并没有解决什么问题

### ISSUE THREAD

**Issue by silentMood** [node-webot/wechat-api#81]

**Comment by silentMood** [comment]
![2015-10-27 2 28 29](https://cloud.githubusercontent.com/assets/5231148/10750988/06509530-7cb7-11e5-98d6-3cbfc278d999.png)

**Comment by JacksonTian** [comment]
不是写了 去调用getAccessToken，然后重试么。

**Comment by silentMood** [comment]
。。。这是我写的

**Comment by silentMood** [comment]
我看下版本。。。

**Comment by silentMood** [comment]
代码里面看，在重试之前，如果代码中的AccessToken().isValid()验证通过，就直接redo。。。 但是我在线上偶尔会发现莫名奇妙在有效期内就过期了，然后就一直跪，在这只算是个hack。。。

**Comment by silentMood** [comment]
完整修改是这样，看是否有问题，或者帮助意义
![2015-10-27 3 33 01](https://cloud.githubusercontent.com/assets/5231148/10752023/7df0389e-7cc0-11e5-80e1-b648ad20e3da.png)

**Comment by JacksonTian** [comment]
和wechat-api写的区别是什么？

**Comment by silentMood** [comment]
区别是一旦出现上述那种在 token有效期内的 40001，就重新获取accessToken然后redo，现有代码在出现这种情况就会一直跪

**Comment by JacksonTian** [comment]
我懂你意思了。我们做的是临界点过期的40001，调用preRequest就会进入getAccessToken的流程，因为下次判断isValid的时候会失败。你这种是意外token失效的情况下 也生效对吧。 但是目前不推荐这样改。因为当你碰到一个集群都去调用刷新accessToken的时候，就跪了。

**Comment by JacksonTian** [comment]
在什么情况下 token会意外失效？建议token统一管理，不要另外再留更新token的入口。

**Comment by silentMood** [comment]
犯懒没仔细查原因，，， 还是仔细查下原因看看。 多谢回复哈

**Comment by JacksonTian** [comment]
那这个issue暂时先关闭了。

**Comment by XGHeaven** [comment]
@silentMood 我现在的做法就是遇到40001错误的时候，手动创建一个队列，让后面的请求都进入队列中，当新的Accesstoken请求完成之后，依次从队列中取出来，然后继续执行。

**Comment by liangwenzhong** [comment]
我也遇到这个问题，微信的accesstoken提早过期了。但是wechat-api单纯判断了有效期，导致一段时间程序会报错。等有效期过了，才能恢复正常。求指点，如何处理？

accesstoken，程序没有去修改，是否微信的机制修改了？
