### ISSUE TITLE
能否将oAuth验证的内容添加到这里面来？

### ISSUE THREAD

**Issue by XGHeaven** [node-webot/wechat-api#90]
就是我需oAuth验证的一些东西，但是我不想在wechat-api使用的情况下再使用wehcat-oauth，请问能否将两个整合在一起？

**Comment by nick-ma** [comment]
你可以在使用的时候把2个库同时引入。 目前没有计划把这2个库合在一起。

**Comment by XGHeaven** [comment]
但是这个两个库的代码几乎就是一样的，只是多了一些不同的东西而已。
同时引入两个库是不是有一些浪费？

**Comment by JacksonTian** [comment]
完全不一样。

**Comment by XGHeaven** [comment]
@JacksonTian 您说的完全不一样是指什么内容？我大体看了一下，基础东西是一样的，完全可以将其作为一个模块mixin入到API中，请问这样不可以么？

**Comment by JacksonTian** [comment]
职责单一，且方便测试。

**Comment by XGHeaven** [comment]
@JacksonTian 哦，我有点明白了，那我就在引入`wechat-oauth`库好了，那我close了~~

**Comment by ghost** [comment]
F:\微信端\WeixinApp\node_modules\_express@4.15.5@express\lib\router\index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

TypeError: Router.use() requires middleware function but got a Object
你们有遇到过这种情况吗？
