### ISSUE TITLE
this.registerTicketHandle is not a function

### ISSUE THREAD

**Issue by HaveF** [node-webot/wechat-api#95]
用的是最新的1.22.0，代码也很简单，部署在了heroku上
```javascript
const WechatAPI = require('wechat-api');
...
...
app.use('/wechat', WechatAPI(config, function (req, res, next) {
  res.send('test');
}));
```
相关的错误log如下：
```
: > generated-express-app@0.0.1 start /app
: > node ./bin/www
:
: /app/node_modules/wechat-api/lib/api_common.js:85
:        ^
:
:   this.registerTicketHandle();
:     at API (/app/node_modules/wechat-api/lib/api_common.js:85:8)
: TypeError: this.registerTicketHandle is not a function
:     at Object.<anonymous> (/app/app.js:17:20)
:     at Function.Module._load (module.js:311:12)
:     at Object.Module._extensions..js (module.js:432:10)
:     at Module._compile (module.js:425:26)
:     at Module.load (module.js:356:32)
:     at Object.<anonymous> (/app/bin/www:3:11)
:     at Module.require (module.js:366:17)
:     at require (module.js:385:17)
:     at Module._compile (module.js:425:26)
```
[api_common.js: 85](https://github.com/node-webot/wechat-api/blob/master/lib/api_common.js#L85)看上去好像也没啥问题，函数是在[api_js.js#L46](https://github.com/node-webot/wechat-api/blob/master/lib/api_js.js#L46)，看了下blame，@xuming314 很久之前commit的，所以估计也不是他那的问题，不知道这个问题究竟出在哪里。小白搞不定:dizzy_face::dizzy_face:
麻烦了，谢谢！:pray::pray::pray:

**Comment by JacksonTian** [comment]
用错了，先读下文档吧。

**Comment by HaveF** [comment]
谢谢大神:heart:，我其实是读了文档的,,,但没读懂，我看`wechat-enterprise`和`wechat`都是这么调用的，所以以为`wechat-api`也这么用。
是不是可以理解为，如果想用`wechat-api`，`wechat`这个中间件是不可缺少的？

另外搭车问下，《深入浅出》异步编程那一章我看的云里雾里的，您有什么建议吗？多看两遍？现在ES6也带promise的情况下，要着重多实践`Promise`吗？

**Comment by XGHeaven** [comment]
@HaveF 随性吧。我比较赞同使用promise，毕竟是一个通用的规范，在其他的语言中同样试用。

**Comment by HaveF** [comment]
@XGHeaven 谢谢:smile:
